# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_auto_20161115_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=32, unique=True)),
                ('picture_url', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
