# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20161116_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
