# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_goods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.UserProfile'),
        ),
    ]
