# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20161206_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_qq',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture_url',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_url',
            field=models.CharField(blank=True, default='http://ershou.u.qiniudn.com/Android_1480732854630_186265.jpg?imageView2/5/w/800/h/800', max_length=128),
        ),
    ]
