# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_goods_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_qq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
