# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20161206_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('comment_time', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.UserProfile')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Goods')),
            ],
        ),
    ]
