# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='from_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Goods'),
        ),
    ]
