# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_goods_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('send_time', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='market.UserProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='market.UserProfile')),
            ],
        ),
    ]
